language: python
python:
  - 3.6.6
install:
  - pip install pipenv
  - pipenv install --system --ignore-pipfile
script:
  - python ./superlists/manage.py test
  
sudo: required
services:
- docker
after_success:
- bin/docker_push.sh
