language: python
python:
  - 3.6.6

addons:
  firefox: latest

sudo: required
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar -xvzf geckodriver*
  - chmod +x geckodriver
  - sudo mv geckodriver /usr/local/bin/
  - pip install pipenv
  - pipenv install --system --ignore-pipfile
script:
  - python ./superlists/manage.py test lists
  - python ./superlists/manage.py test functional_tests
  
services:
- docker
after_success:
- bash bin/ecr_credentials.sh
- bash bin/docker_push.sh
